### ISSUE TITLE
Backend Interval Jobs Need to Switch to Cron Jobs

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/monorepo#11]
Title!

In the past, we were going to use [Bree](https://github.com/breejs/bree) for this. Are there any preferable alternatives or do we like this one?

**Comment by maybesmurf** [comment]
Bullmq. But this required a redis instance. I'd be more than glad to implement this

**Comment by kamalyusuf** [comment]
bullmq, but this requires redis. i'd be more than glad to implement this

**Comment by kamalyusuf** [comment]
bullmq but it requires a redis instance

**Comment by anthonyshew** [comment]
Hm, that's out then! 😁 No need to bloat the stack just to run a cron job!
