### ISSUE TITLE
Schedules not showing up on profile pages!

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/monorepo#168]
The Twitch API changed so we need to make an adjustment.

**Comment by booleans-oss** [comment]
closed with aae1f54d4f6c18b88749418bbf4eb9e6c610834b

**Comment by booleans-oss** [comment]
The API endpoint seems correct. But I'm not sure for the filter of ``is_recurring``. Maybe try removing it and see what happens

**Comment by anthonyshew** [comment]
Yes! The payloads have changed unexpectedly, I believe, Am investigating this now.

**Comment by anthonyshew** [comment]
Turns out I was wrong about this! They are working but I was improperly throwing an error for when a user doesn't have a schedule.

Closing!
