### ISSUE TITLE
Nitpicks: API

### ISSUE THREAD

**Issue by indifferentghost** [kittrgg/monorepo#20]
# API

- Might want to add an allow list for cors agents. [index.js#8](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/index.js#L8)  [index.js#14](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/index.js#L14)

- Can we do a dynamic variable to import `rollbar` based on if an ENV_VARIABLE is enabled? [index.js#25-31](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/index.js#L25-L31) [index.js#37-39](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/index.js#L37-L39)

- We can relate object ids to particular models a la: `gameId: { type: Schema.Types.ObjectId, ref: 'game' },` [models/KitBase.js#8](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/models/KitBase.js#L8)

- Should `gameId` be an ObjectId? https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/models/KitOption.js#L6

- We can do tighter mongoose models ([models/Player.js@14-15](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/models/Player.js#L14-L15), [models/Player.js@41-42](https://github.com/kittrgg/monorepo/blob/e43eab0531eaaca262539e269e12e0a4c9e79fe6/api/models/Player.js#L41-L42))

**Comment by anthonyshew** [comment]
`We can relate object ids to particular models`

I haven't seen this before; what benefits does this provide?

**Comment by anthonyshew** [comment]
Addressed in #219.
