### ISSUE TITLE
Add a LICENSE.txt

### ISSUE THREAD

**Issue by exaby73** [kittrgg/monorepo#7]
You should add a LICENSE file to protect the intellectual property and code of this product. I recomment [GPL v3](https://choosealicense.com/licenses/gpl-3.0/) but it's your choice @anthonyshew :)

**Comment by anthonyshew** [comment]
Added in 269c5a337c21908fa8ddc9f1b7daf5a88c8b9d97!

Thanks, ex, good looks.
