### ISSUE TITLE
Must install node packages before running docker-compose?

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/monorepo#84]
Someone reported that they have to manually install the node packages on their machine before they are able to run the docker-compose! I thought that the docker containers were installing their deps themselves but...

Apparently I am using volumes or writing the Dockerfiles incorrectly...

**Comment by jonbrook** [comment]
If you remove the volumes for both api and web from the docker-compose the build should work as expected

**Comment by anthonyshew** [comment]
Ah, interesting! I believe the problem there is that the live reloading capabilities of these two folders depend on those volumes. But thanks for the info, I'll use that to try to figure out what I can do. Probably going to only bring on volumes for the actual source code. 🤔

**Comment by anthonyshew** [comment]
During our investigation of this issue, we figured that @jonbrook was indeed correct!

The interesting part is that you do indeed need the `node_modules` folders installed locally so that your IDE (or at least VSCode) will be aware of the TS types for the project and its deps.

The current fix is:
- Added a `dev:install` script and added it to the README for a new dev's initial setup
- Excluded `node_modules` from the various containers
