### ISSUE TITLE
.env.local.example doesn't exist for `web` folder for Next

### ISSUE THREAD

**Issue by exaby73** [kittrgg/monorepo#90]
Some environment variables are used in Next with Next by default looking for a `env.local` file in it's root project i.e. the web folder. 

We should include a file `web/.env.local.example` but this would cause us to have to maintain 2 env files. Instead, I propose to make the Docker script to copy the root `.env` file to the web folder as `.env.local` and use a single source of truth env file

**Comment by anthonyshew** [comment]
This as a regression!

You're not supposed to need a .env.local at all. The environment variables should be coming from the docker-compose itself.

Will investigate...right now!

**Comment by anthonyshew** [comment]
Turned out to be a non-issue. Luh yew, @exaby73 . :)
